package main

import (
	"projectGoLive/application/config"
	"projectGoLive/application/start"

	_ "github.com/go-sql-driver/mysql"
)

func main() {
	//Handle any panics generated by all packages and log into the error log
	defer func() {
		if err := recover(); err != nil {
			config.Error.Println(err)
		}
	}()

	start.StartApplication()
}
